### ISSUE TITLE
When using assigning identities, some cell annotation labels are missing for the UCell method 

### ISSUE THREAD

**Issue by cathalgking** [gdagstn/cellula#2]
When using the UCell method of cell annotation with assignIdentities(), some of the genes are missing. The AUC method seems to include all of the gene sets when the exact same SCE object and geneset is used. A warning message is given as shown below.

![Screen Shot 2023-07-31 at 10 51 26 am](https://github.com/gdagstn/cellula/assets/32261323/2c2d8d49-dbcd-452a-801a-ee8ed01c69d6)

`[ANNO/UCell] Calculating UCell scores 
Warning: The following genes were not found and will be
                        imputed to exp=0:
* CLEC4OP,RYR3-DT,DYNLT5,ENSG00000225792,ENSG00000226780,ENSG00000229425,ENSG00000234432,H2AW,ITGB8-AS1,UBR5-DT,ENSG00000233968,CDK6-AS1,CFAP251,ENSG00000263667,ENSG00000264269,H1-2,H2BC8,AQP5-AS1,DNMT3L-AS1,ENSG00000227220,ENSG00000236166,LOC100506688,RFX5-AS1,ZNF22-AS1,ENSG00000230537,CRYM-AS1,LCT-AS1,LOC105377488,NOPCHAP1,PAPLN-AS1,ATP5MK,PGAP4,H1-10,H1-4,H2AJ,RNASE2CP,AARS1,BSG-AS1,CRACD,DYNC2I2,ENSG00000189316,EPRS1,EPS15-AS1,GARS1,GFUS,H1-0,H1-3,HARS1,IARS1,IFTAP,LARS1,MACIR,METTL13,MIX23,NARS1,POLR1G,RARS1,SLC30A6-DT,SLX9,TARS1,VARS1,ZNF788P,ENSG00000230709,MARCHF1,PLEKHG7,CCL3L3,CYRIA,H3-3B,PELATON,PTPRN2-AS1,WARS1,ANKRD44-AS1,CARS1,CUTALP,DCTN6-DT,PARP11-AS1,PP7080,PRKCH-AS1,RAB33B-AS1,ATP5MJ,ENSG00000238005,ENSG00000238142,GPX1,MIR223HG,MIR23AHG,MTARC1,CYRIB,ENSG00000167912,ENSG00000265206,IRF1-AS1,KIR3DX1,LINC00869,LINC02481,TFAP2E-AS1,CIBAR2,DTNB-AS1,ENSG00000249679,ENSG00000253633,ENSG [... truncated]`

**Comment by gdagstn** [comment]
Hi Cathal, thanks for reporting. 

Would you mind checking how the geneset intersects with the rownames of your object? 

Something like:

`lapply(genesets, function(x) table(x %in% rownames(sce)))` 

where `genesets` is the list containing the Hay bone marrow sets.

**Comment by cathalgking** [comment]
```> result <- lapply(genesets, function(x) table(x %in% rownames(sce)))
> str(result)
List of 700
 $ AIZARANI_LIVER_C1_NK_NKT_CELLS_1                                          : 'table' int [1(1d)] 195
  ..- attr(*, "dimnames")=List of 1
  .. ..$ : chr "TRUE"
 $ AIZARANI_LIVER_C10_MVECS_1                                                : 'table' int [1:2(1d)] 6 287
  ..- attr(*, "dimnames")=List of 1
  .. ..$ : chr [1:2] "FALSE" "TRUE"
 $ AIZARANI_LIVER_C11_HEPATOCYTES_1                                          : 'table' int [1:2(1d)] 3 327
  ..- attr(*, "dimnames")=List of 1
  .. ..$ : chr [1:2] "FALSE" "TRUE"
 $ AIZARANI_LIVER_C12_NK_NKT_CELLS_4                                         : 'table' int [1(1d)] 59
  ..- attr(*, "dimnames")=List of 1
  .. ..$ : chr "TRUE"
 $ AIZARANI_LIVER_C13_LSECS_2                                                : 'table' int [1:2(1d)] 9 301
  ..- attr(*, "dimnames")=List of 1
  .. ..$ : chr [1:2] "FALSE" "TRUE"`
  ```
  
```> head(result)
$AIZARANI_LIVER_C1_NK_NKT_CELLS_1

TRUE 
 195 

$AIZARANI_LIVER_C10_MVECS_1

FALSE  TRUE 
    6   287 

$AIZARANI_LIVER_C11_HEPATOCYTES_1

FALSE  TRUE 
    3   327 

$AIZARANI_LIVER_C12_NK_NKT_CELLS_4

TRUE 
  59 

$AIZARANI_LIVER_C13_LSECS_2

FALSE  TRUE 
    9   301 

$AIZARANI_LIVER_C14_HEPATOCYTES_2

FALSE  TRUE 
    2   263 ```

**Comment by gdagstn** [comment]
ok it sounds like there aren't many genes missing for every signature - I'd say you can proceed as usual. if you see very weird results let me know!

**Comment by cathalgking** [comment]
This worked with the following:
`sce = assignIdentities(sce, genesets = plasma_genes, method = "UCell", name = "UCell_plasma")`
Thanks
